version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: codeplatform-db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s

  pgadmin:
    image: dpage/pgadmin4
    container_name: codeplatform-pgadmin
    env_file: .env
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg_data: